### ISSUE TITLE
Ultimate-Awesome-Transformer-Attention

### ISSUE THREAD

**Issue by cmhungsteve** [automl/awesome-transformer-search#4]
Thank you for sharing this great list!

I would like to share a CV/ML paper list mainly about Vision Transformer & Attention made by myself:
https://github.com/cmhungsteve/Awesome-Transformer-Attention

I would be appreciative if you can add the list to the "Misc resources" Section.
Thank you!

**Comment by yashsmehta** [comment]
Yep, have added it to the Misc Resources section!

**Comment by cmhungsteve** [comment]
Thank you, @yashsmehta !
